139 notifications add two versions of each email for admins and users
wpappointments/wpappointments pull request #156
Opened 2024-03-01 14:08 UTC by marcinkrzeminski

2024-03-01 14:56 UTC, dawidurbanski requested changes
This works and PR looks great. Just one thing. It only added sending two emails (one for admin and one for customer), to the "appointment created" action.

We want the same for all the other actions.

- [x] Appointment created
    - [x] admin
    - [x] user
- [ ] Appointment updated
    - [ ] admin
    - [x] user
- [ ] Appointment cancelled
    - [ ] admin
    - [x] user
- [ ] Appointment no show
    - [ ] admin
    - [x] user
- [ ] Appointment confirmed
    - [ ] admin
    - [x] user

2024-03-01 17:19 UTC, marcinkrzeminski commented
@dawidurbanski please check again. Admin notifications covered for all types of emails.

2024-03-03 14:56 UTC, dawidurbanski commented on assets/backend/admin/components/AppointmentsTableFull/AppointmentsTableFull.tsx
> +					{row.status.replace('_', ' ')}
nie ma potrzeby robić tego replace tak?

2024-03-03 14:57 UTC, dawidurbanski approved these changes
LGTM

2024-03-03 14:57 UTC, merged